Introduction

What is pandas ?
pandas is a powerful python data analysis toolkit.
open source.
A fast and effcient Dataframe object for data manipulation.
Reading and writing data structures and different formats : csv, txt, xml, json, sql, zip, pickle, sas etc.

Pandas vs Excel
Excel - Fill missing data manually
Pandas - Fill millions of data using pandas


Pandas Data structure
Series - Single dimesional label data. Homogenous array.
datataframe - Two dimensional tabular format data. hetrogenous array.

Installation of Pandas


pip install pandas

# How to use pandas library

In [142]:
import pandas as pd

# Create series

In [143]:
#create series 
list1 = [10,20,30,40,50]
print(list1)
print("-----------------")
pd.Series(list1)

[10, 20, 30, 40, 50]
-----------------

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [147]:
#create series with index

pd.Series(list1, index=['a','b','c','d','e'] )

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [148]:
#create series with dtype

pd.Series(list1, index=['a','b','c','d','e'], dtype=float )

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
dtype: float64

In [149]:
#create series with dtype

pd.Series(list1, index=['a','b','c','d','e'], dtype=str )

a    10
b    20
c    30
d    40
e    50
dtype: object

In [150]:
#create series with dtype

pd.Series(list1, index=['a','b','c','d','e'], dtype=bool)

a    True
b    True
c    True
d    True
e    True
dtype: bool

In [151]:
#create series with series name


x = pd.Series(list1, index=['a','b','c','d','e'], dtype=float, name='Data Values' )
x

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
Name: Data Values, dtype: float64

In [152]:
#create series using scaler


pd.Series(0.5, index=['a','b','c','d','e','f','g','h','i','j'])

a    0.5
b    0.5
c    0.5
d    0.5
e    0.5
f    0.5
g    0.5
h    0.5
i    0.5
j    0.5
dtype: float64

In [153]:
#create series using dictionary
pd.Series({'a':1,'b':2,'c':3,'d':4})

a    1
b    2
c    3
d    4
dtype: int64

In [154]:
pd.Series({1:'a',2:'b',3:'c',4:'d'})

1    a
2    b
3    c
4    d
dtype: object

# Indexing and Slicing in Series

In [155]:
a = pd.Series([100,200,300,400,500])
a

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [156]:
a[2]

300

In [157]:
a[2:8]

2    300
3    400
4    500
dtype: int64

In [158]:
a[2::2]

2    300
4    500
dtype: int64

In [164]:
a[-1:]

4    500
dtype: int64

In [166]:
a[:-1]

0    100
1    200
2    300
3    400
dtype: int64

In [167]:
a[::-1]

4    500
3    400
2    300
1    200
0    100
dtype: int64

In [168]:
max(a)

500

In [169]:
min(a)

100

In [170]:
a[a > 200]

2    300
3    400
4    500
dtype: int64

In [171]:
a>200

0    False
1    False
2     True
3     True
4     True
dtype: bool

# Mathematical Operation

In [172]:
a

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [173]:
b = pd.Series([5,10,15,20])
b

0     5
1    10
2    15
3    20
dtype: int64

In [174]:
print(a + b)

0    105.0
1    210.0
2    315.0
3    420.0
4      NaN
dtype: float64

In [175]:
a-b

0     95.0
1    190.0
2    285.0
3    380.0
4      NaN
dtype: float64

In [176]:
print(a)
print(b)

0    100
1    200
2    300
3    400
4    500
dtype: int64
0     5
1    10
2    15
3    20
dtype: int64

In [177]:
a//b

0    20.0
1    20.0
2    20.0
3    20.0
4     NaN
dtype: float64

In [178]:
#unmatched data values


c = pd.Series([1,2,3])
print(a)
print(b)
print(c)

0    100
1    200
2    300
3    400
4    500
dtype: int64
0     5
1    10
2    15
3    20
dtype: int64
0    1
1    2
2    3
dtype: int64

In [179]:
b+c

0     6.0
1    12.0
2    18.0
3     NaN
dtype: float64

In [182]:
b+c>=b+c

0     True
1     True
2     True
3    False
dtype: bool

In [183]:
b+c==b+c

0     True
1     True
2     True
3    False
dtype: bool

# DataFrame In Pandas

In [184]:
list1 = [10,20,30,40,50]
list1

[10, 20, 30, 40, 50]

In [185]:
pd.DataFrame(list1)

    0
0  10
1  20
2  30
3  40
4  50

In [186]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [187]:
import numpy as np
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [188]:
pd.DataFrame(list2)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

# Creating DataFrame Using Dict

In [189]:
dict1 = {'id':[1,2,3], 'id1':[11,12,13]}
dict1

{'id': [1, 2, 3], 'id1': [11, 12, 13]}

In [190]:
df1 = pd.DataFrame(dict1)
df1

   id  id1
0   1   11
1   2   12
2   3   13

# Create DataFrame Using Dict in list

In [191]:
dict2 = [{1:'a',2:'b',3:'c'},{1:'aa',2:'bb',3:'cc',4:"dd"},{1:'a',2:'b',3:'c'}]
dict2

[{1: 'a', 2: 'b', 3: 'c'},
 {1: 'aa', 2: 'bb', 3: 'cc', 4: 'dd'},
 {1: 'a', 2: 'b', 3: 'c'}]

In [194]:
df2 = pd.DataFrame(dict2)
df2

    1   2   3    4
0   a   b   c  NaN
1  aa  bb  cc   dd
2   a   b   c  NaN

# Creating dataframe of dict of series

In [195]:
dict3 = {'A': pd.Series([10,20,30,40,50]), 'B': pd.Series([100,200,300,400])}
dict3

{'A': 0    10
 1    20
 2    30
 3    40
 4    50
 dtype: int64,
 'B': 0    100
 1    200
 2    300
 3    400
 dtype: int64}

In [196]:
df3 = pd.DataFrame(dict3)
df3

    A      B
0  10  100.0
1  20  200.0
2  30  300.0
3  40  400.0
4  50    NaN

# What is CSV file

In [ ]:
# READ CSV file
# Comma - Separated Values
# read_csv()

In [197]:
import pandas as pd


df = pd.read_csv('Movieratingdata.csv') 
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [198]:
#find datatype
type(df)

pandas.core.frame.DataFrame

In [199]:
df['USER_ID'].dtype

dtype('int64')

In [200]:
#find columns name
df.columns

Index(['USER_ID', 'MOVIE_ID', 'MOVIE_TITLE', 'PRODUCTION_YEAR', 'GENRES',
       'RATING', 'Unnamed: 6', 'Unnamed: 7', 'GENRES.1', 'Unnamed: 9'],
      dtype='object')

In [201]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   USER_ID          500 non-null    int64
 1   MOVIE_ID         500 non-null    int64
 2   MOVIE_TITLE      500 non-null    object
 3   PRODUCTION_YEAR  500 non-null    int64
 4   GENRES           500 non-null    object
 5   RATING           500 non-null    float64
 6   Unnamed: 6       0 non-null      float64
 7   Unnamed: 7       2 non-null      float64
 8   GENRES.1         5 non-null      object
 9   Unnamed: 9       4 non-null      float64
dtypes: float64(4), int64(3), object(3)
memory usage: 39.2+ KB

# nrow

In [207]:
#print number of rows


data = 'Movieratingdata.csv'
df = pd.read_csv(data, nrows=10)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4,NaN,NaN,adventures,NaN
5,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5,NaN,NaN,NaN,NaN
6,7,2719848,Everest,2015,Action|Adventure|Biography|Drama|Thriller,6,NaN,NaN,NaN,NaN
7,8,462504,Rescue Dawn,2006,Action|Adventure|Biography|Drama|War,8,NaN,NaN,NaN,NaN
8,9,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,10,NaN,NaN,NaN,NaN
9,10,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9,NaN,NaN,NaN,NaN

# usecols

In [208]:
#print specific columns using usecol parameters


df = pd.read_csv(data, usecols=[0,3,5])
df

     USER_ID  PRODUCTION_YEAR  RATING
0          1             2015     8.0
1          2             2013     5.0
2          3             2005     9.0
3          4             2015     5.0
4          5             2018     4.0
..       ...              ...     ...
495      496             2018     6.0
496      497             2016     6.0
497      498             2019     7.0
498      499             2019     4.0
499      500             2013     1.0

[500 rows x 3 columns]

# skiprows

In [209]:
#skip rows


df = pd.read_csv(data, skiprows=[1,4,8,30,50])
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
1,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
2,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
3,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5.0,NaN,NaN,NaN,NaN
4,7,2719848,Everest,2015,Action|Adventure|Biography|Drama|Thriller,6.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
490,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
491,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
492,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
493,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
494,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [210]:
#skip specfic rows - `skiprows`


df = pd.read_csv(data, skiprows=[1,3,20,30])
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
1,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
2,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
3,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5.0,NaN,NaN,NaN,NaN
4,7,2719848,Everest,2015,Action|Adventure|Biography|Drama|Thriller,6.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
491,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
492,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
493,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
494,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
495,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

# index_col

In [ ]:
#use columns as a index


df = pd.read_csv(data, index_col="USER_ID")
df

In [ ]:
#multiple columns make as a index using indexing number


df = pd.read_csv(data, index_col=[0,1,2,3])
df

In [ ]:
df.shape

# header

In [286]:
# make any rows as a header


df = pd.read_csv(data)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [287]:
df = pd.read_csv(data, header= 10)
df

,10,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,11,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9.2,NaN,NaN,NaN,NaN
1,12,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,6.0,NaN,NaN,NaN,NaN
2,13,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9.0,NaN,NaN,NaN,NaN
3,14,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,8.0,NaN,NaN,NaN,NaN
4,15,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,7.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
485,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
486,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
487,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
488,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
489,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [288]:
#use new name for column heading


df = pd.read_csv(data, header=None )
df

,0,1,2,3,4,5,6,7,8,9
0,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,NaN,NaN,GENRES,NaN
1,1,4642044,Riot,2015,Action,8,NaN,1.0,action,8.0
2,2,1925518,The Protector 2,2013,Action,5,NaN,5.0,suspense,6.0
3,3,372784,Batman Begins,2005,Action|Adventure,9,NaN,NaN,drama,5.0
4,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5,NaN,NaN,thriller,4.0
...,...,...,...,...,...,...,...,...,...,...
496,496,1846589,Hunter Killer,2018,Action|Thriller,6,NaN,NaN,NaN,NaN
497,497,4196776,Jason Bourne,2016,Action|Thriller,6,NaN,NaN,NaN,NaN
498,498,7456310,Anna,2019,Action|Thriller,7,NaN,NaN,NaN,NaN
499,499,8106534,6 Underground,2019,Action|Thriller,4,NaN,NaN,NaN,NaN
500,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1,NaN,NaN,NaN,NaN

In [291]:
# use different name for different columns


df = pd.read_csv(data, names=['A','b','c','d','e','f','g','h'])
df

,,A,b,c,d,e,f,g,h
USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,NaN,NaN,GENRES,NaN
1,4642044,Riot,2015,Action,8,NaN,1.0,action,8.0
2,1925518,The Protector 2,2013,Action,5,NaN,5.0,suspense,6.0
3,372784,Batman Begins,2005,Action|Adventure,9,NaN,NaN,drama,5.0
4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5,NaN,NaN,thriller,4.0
...,...,...,...,...,...,...,...,...,...
496,1846589,Hunter Killer,2018,Action|Thriller,6,NaN,NaN,NaN,NaN
497,4196776,Jason Bourne,2016,Action|Thriller,6,NaN,NaN,NaN,NaN
498,7456310,Anna,2019,Action|Thriller,7,NaN,NaN,NaN,NaN
499,8106534,6 Underground,2019,Action|Thriller,4,NaN,NaN,NaN,NaN
500,2302755,Olympus Has Fallen,2013,Action|Thriller,1,NaN,NaN,NaN,NaN

# head()

In [292]:
#show the only five rows


df = pd.read_csv(data)
df.head()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN

# tail()

In [293]:
#Show the last five rows


df = pd.read_csv(data)
df.tail()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [294]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   USER_ID          500 non-null    int64
 1   MOVIE_ID         500 non-null    int64
 2   MOVIE_TITLE      500 non-null    object
 3   PRODUCTION_YEAR  500 non-null    int64
 4   GENRES           500 non-null    object
 5   RATING           500 non-null    float64
 6   Unnamed: 6       0 non-null      float64
 7   Unnamed: 7       2 non-null      float64
 8   GENRES.1         5 non-null      object
 9   Unnamed: 9       4 non-null      float64
dtypes: float64(4), int64(3), object(3)
memory usage: 39.2+ KB

In [295]:
#change numeric columns dtype


df = pd.read_csv(data, dtype={'USER_ID':'object'})
df.head()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN

In [296]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   USER_ID          500 non-null    object
 1   MOVIE_ID         500 non-null    int64
 2   MOVIE_TITLE      500 non-null    object
 3   PRODUCTION_YEAR  500 non-null    int64
 4   GENRES           500 non-null    object
 5   RATING           500 non-null    float64
 6   Unnamed: 6       0 non-null      float64
 7   Unnamed: 7       2 non-null      float64
 8   GENRES.1         5 non-null      object
 9   Unnamed: 9       4 non-null      float64
dtypes: float64(4), int64(2), object(4)
memory usage: 39.2+ KB

# Handling Missing Values

In [297]:
import pandas as pd
df = pd.read_csv('Movieratingdata1.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

# na_values

In [298]:
#change numeric columns dtype


df = pd.read_csv('Movieratingdata1.csv' , na_values=[4642044])
df.head() 
# df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,NaN,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4

In [299]:
#change numeric columns dtype


df = pd.read_csv('Movieratingdata1.csv' , na_values={'MOVIE_ID':1663202})
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,NaN,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,NaN,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [300]:
df = pd.read_csv('Movieratingdata1.csv', keep_default_na=True)
df.head(15)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

# isnull()

In [301]:
#showing null values in true or false structure
df = pd.read_csv('Movieratingdata1.csv')
df
df.isnull()

    USER_ID  MOVIE_ID  MOVIE_TITLE  PRODUCTION_YEAR  GENRES  RATING
0     False     False        False            False   False    True
1      True      True         True             True    True    True
2     False     False         True            False    True    True
3     False     False         True            False    True   False
4     False     False         True            False   False   False
5     False     False         True            False   False   False
6     False     False         True            False   False   False
7     False     False         True            False   False   False
8     False      True         True            False   False   False
9     False     False        False            False   False   False
10    False     False         True            False   False   False
11    False     False        False            False   False   False

# isnull().sum()

In [302]:
#total null values in single columns


df = pd.read_csv('Movieratingdata1.csv')
#df.head(10) 
df.isnull().sum()

USER_ID            1
MOVIE_ID           2
MOVIE_TITLE        9
PRODUCTION_YEAR    1
GENRES             3
RATING             3
dtype: int64

# isnull().sum().sum()

In [303]:
#total null values in dataset


df = pd.read_csv('Movieratingdata1.csv')
df.head(10) 
df.isnull().sum().sum()

19

# notnull()

In [304]:
#opposite isnull()


df = pd.read_csv('Movieratingdata1.csv')
# df.head(10) 
df.notnull().sum().sum()

53

# dropna()

In [217]:
#remove missing values


df = pd.read_csv('Movieratingdata1.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [305]:
df = pd.read_csv('Movieratingdata1.csv')
df.dropna()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [306]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [307]:
#remove missing values for column


df = pd.read_csv('Movieratingdata1.csv')
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# how={'any', 'all'}

In [308]:
#remove missing values


df = pd.read_csv('Movieratingdata1.csv')
df.dropna(how='all')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [222]:
#remove missing values


df = pd.read_csv('Movieratingdata1.csv')
df.dropna(how='any')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

# thresh

In [223]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [314]:
#remove missing values thresh takes integer value which tells 
# minimum amount of non null values to drop.

import pandas as pd
df = pd.read_csv('Movieratingdata1.csv')
df.dropna(axis=0, thresh=2)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [230]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [325]:
#remove missing values in specific columns

import pandas as pd
df = pd.read_csv('Movieratingdata1.csv')
df.dropna(subset=['MOVIE_TITLE'],inplace = False)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [326]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [327]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

# inplace

In [352]:
#remove missing values in specific columns


df = pd.read_csv('Movieratingdata1.csv')
# df.dropna(inplace=False)


df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [351]:
df.dropna(inplace=True)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [348]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [349]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [353]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1.0,4642044,Riot,2015,Action,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,not value,NaN,2014,NaN,NaN
3,4.0,1390411,NaN,2015,NaN,5
4,5.0,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6.0,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7.0,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8.0,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9.0,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10.0,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11.0,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12.0,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

# pandas fillna() method

In [411]:
df = pd.read_csv('Movieratingdata2.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,NaN,Riot,2015,Action,8
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,Not available value,NaN,NaN,NaN
3,4,1390411,NaN,NaN,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2015,Action|Adventure|Biography|Drama|Western,10
9,10,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [412]:
# value : scalar, dict, 


df.fillna(11)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,11,Riot,2015,Action,8
1,2,11,11,11,11,11
2,3,not value,Not available value,11,11,11
3,4,1390411,11,11,11,5
4,5,6306064,11,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,11,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,11,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,11,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,11,11,2015,Action|Adventure|Biography|Drama|Western,10
9,10,11,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [413]:
df.fillna({"MOVIE_ID":1000,'MOVIE_TITLE':'Riot2', 'PRODUCTION_YEAR':2050})

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,1000,Riot,2015,Action,8
1,2,1000,Riot2,2050,NaN,NaN
2,3,not value,Not available value,2050,NaN,NaN
3,4,1390411,Riot2,2050,NaN,5
4,5,6306064,Riot2,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Riot2,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Riot2,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,Riot2,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,1000,Riot2,2015,Action|Adventure|Biography|Drama|Western,10
9,10,1000,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [414]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,NaN,Riot,2015,Action,8
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,Not available value,NaN,NaN,NaN
3,4,1390411,NaN,NaN,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2015,Action|Adventure|Biography|Drama|Western,10
9,10,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

# fillna(method ="ffill")

In [415]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,NaN,Riot,2015,Action,8
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,Not available value,NaN,NaN,NaN
3,4,1390411,NaN,NaN,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2015,Action|Adventure|Biography|Drama|Western,10
9,10,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [416]:
# df.fillna(method='ffill') 
#forward fill
df.ffill()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,NaN,Riot,2015,Action,8
1,2,NaN,Riot,2015,Action,8
2,3,not value,Not available value,2015,Action,8
3,4,1390411,Not available value,2015,Action,5
4,5,6306064,Not available value,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Not available value,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Not available value,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,Not available value,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,462504,Not available value,2015,Action|Adventure|Biography|Drama|Western,10
9,10,462504,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

# fillna(method="bfill")

In [268]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,NaN,Riot,2015,Action,8
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,Not available value,NaN,NaN,NaN
3,4,1390411,NaN,NaN,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2015,Action|Adventure|Biography|Drama|Western,10
9,10,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [267]:
# df.fillna(method='bfill') #backward fill
df.bfill()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,not value,Riot,2015,Action,8
1,2,not value,Not available value,not available,Action|Adventure|Biography|Drama|Romance|Thriller,5
2,3,not value,Not available value,not available,Action|Adventure|Biography|Drama|Romance|Thriller,5
3,4,1390411,The Revenant,not available,Action|Adventure|Biography|Drama|Romance|Thriller,5
4,5,6306064,The Revenant,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,The Revenant,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,The Revenant,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,The Revenant,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,10
9,10,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

# fillna( axis=0 or 1)

In [269]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,NaN,Riot,2015,Action,8
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,Not available value,NaN,NaN,NaN
3,4,1390411,NaN,NaN,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2015,Action|Adventure|Biography|Drama|Western,10
9,10,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [270]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,NaN,Riot,2015,Action,8
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,Not available value,NaN,NaN,NaN
3,4,1390411,NaN,NaN,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2015,Action|Adventure|Biography|Drama|Western,10
9,10,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [356]:
#fill forward values in rows
# df.fillna(method='ffill', axis=0)
df.ffill(axis=1)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,1,Riot,2015,Action,8
1,2,2,2,2,2,2
2,3,not value,Not available value,Not available value,Not available value,Not available value
3,4,1390411,1390411,1390411,1390411,5
4,5,6306064,6306064,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,6306064,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,2719848,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,462504,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,9,9,2015,Action|Adventure|Biography|Drama|Western,10
9,10,10,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [273]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,NaN,Riot,2015,Action,8
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,Not available value,NaN,NaN,NaN
3,4,1390411,NaN,NaN,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2015,Action|Adventure|Biography|Drama|Western,10
9,10,NaN,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [274]:
df.bfill(axis=1)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,Riot,Riot,2015,Action,8
1,2.0,NaN,NaN,NaN,NaN,NaN
2,3,not value,Not available value,NaN,NaN,NaN
3,4,1390411,5,5,5,5
4,5,6306064,not available,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,not mension,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,2015,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,2006,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,2015,2015,2015,Action|Adventure|Biography|Drama|Western,10
9,10,The Revenant,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9

In [419]:
#fill forward values in columns


df = pd.read_csv('Movieratingdata3.csv')
# df.fillna(method='bfill', axis=1)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Ironman,NaN,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Ironman,NaN,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Ironman,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,9

In [420]:
df.fillna(2015, limit= 50)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Ironman,2015.0,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Ironman,2015.0,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Ironman,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,9

In [421]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Ironman,NaN,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Ironman,NaN,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Ironman,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,9

In [422]:
#not creating new dataframe , update dataframe only


df.fillna(50, inplace=True)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Ironman,50.0,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Ironman,50.0,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Ironman,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,9

In [423]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Ironman,50.0,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Ironman,50.0,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Ironman,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,9

# pandas replace() method

In [424]:
df = pd.read_csv('Movieratingdata3.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Ironman,NaN,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Ironman,NaN,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Ironman,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,9

In [398]:
#change old value to new value

df.replace("Ironman", "Avengers Series")

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Avengers Series,NaN,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Avengers Series,NaN,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Avengers Series,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Avengers Series,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Avengers Series,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Avengers Series,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,9

In [426]:
#change old value to new value

df.replace(["Ironman","tiger"], ["Don","Tiger Jinda Hai"])

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Don,NaN,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Don,NaN,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Don,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Don,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Don,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Don,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,Tiger Jinda Hai,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,Tiger Jinda Hai,2015.0,Action|Adventure|Biography|Drama|Western,9

In [400]:
#change old value to new value


df.replace(to_replace=[1,2,3,4,5,6,7,8,9,10], value=0)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,0,4642044,Riot,2015.0,Action,0
1,0,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,0
2,0,1245897,Ironman,NaN,Action|Adventure|Biography|Drama|War,0
3,0,1390411,Ironman,NaN,Action|Adventure|Biography|Drama|Western,0
4,0,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,0
5,0,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,0
6,0,2719848,Ironman,2015.0,Action|Adventure|Biography|Drama|Thriller,0
7,0,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,0
8,0,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,0
9,0,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,0

In [385]:
#replace value in specific columns


df.replace({'PRODUCTION_YEAR':2015}, 2021)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2021.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Ironman,NaN,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Ironman,NaN,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Ironman,2021.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2021.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2021.0,Action|Adventure|Biography|Drama|Western,9

In [428]:
#convert all string values in integer using Regex parameter


df.replace('[A-Za-z]',10,regex=True)

   USER_ID  MOVIE_ID  MOVIE_TITLE  PRODUCTION_YEAR  GENRES  RATING
0        1   4642044           10           2015.0      10       8
1        2   2536598           10           2016.0      10       6
2        3   1245897           10              NaN      10       8
3        4   1390411           10              NaN      10       5
4        5   6306064           10           2019.0      10       4
5        6   6306064           10           2020.0      10       5
6        7   2719848           10           2015.0      10       9
7        8    462504           10           2006.0      10       9
8        9     25468           10           2015.0      10      10
9       10   2564789           10           2015.0      10       9

In [388]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,8
1,2,2536598,Ravan,2016.0,Action|Adventure|Biography|Drama|Thriller,6
2,3,1245897,Ironman,NaN,Action|Adventure|Biography|Drama|War,8
3,4,1390411,Ironman,NaN,Action|Adventure|Biography|Drama|Western,5
4,5,6306064,Ironman,2019.0,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Ironman,2020.0,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Ironman,2015.0,Action|Adventure|Biography|Drama|Thriller,9
7,8,462504,Ironman,2006.0,Action|Adventure|Biography|Drama|War,9
8,9,25468,tiger,2015.0,Action|Adventure|Biography|Drama|Western,10
9,10,2564789,tiger,2015.0,Action|Adventure|Biography|Drama|Western,9

In [429]:
#replace using method


df = pd.read_csv('MovieratingdataLOC-ILOC.csv')
df

         DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1    JAN   4642044             2015      10
1   25-2-2021        2    FEB   4642044             2020       6
2   25-3-2021        3    MAR   1245897             2014       8
3   25-4-2021        4  APRIL   1390411             2015       6
4   25-5-2021        5    MAY   6306064             2022       4
5   25-6-2021        6    JUN   6306064             2020       4
6   25-7-2021        7   JULY   2719848             2015       4
7   25-8-2021        8    AUG    462504             2006       9
8   25-9-2021        9   SEPT     25468             2015       6
9  25-10-2021       10    OCT   2564789             2015       9

In [391]:
df.replace(2015, method='ffill')

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\3247565086.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(2015, method='ffill')

         DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1    JAN   4642044             2015      10
1   25-2-2021        2    FEB   4642044             2020       6
2   25-3-2021        3    MAR   1245897             2014       8
3   25-4-2021        4  APRIL   1390411             2014       6
4   25-5-2021        5    MAY   6306064             2022       4
5   25-6-2021        6    JUN   6306064             2020       4
6   25-7-2021        7   JULY   2719848             2020       4
7   25-8-2021        8    AUG    462504             2006       9
8   25-9-2021        9   SEPT     25468             2006       6
9  25-10-2021       10    OCT   2564789             2006       9

In [392]:
df.replace(2015,method="bfill")

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\976846010.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(2015,method="bfill")

         DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1    JAN   4642044             2020      10
1   25-2-2021        2    FEB   4642044             2020       6
2   25-3-2021        3    MAR   1245897             2014       8
3   25-4-2021        4  APRIL   1390411             2022       6
4   25-5-2021        5    MAY   6306064             2022       4
5   25-6-2021        6    JUN   6306064             2020       4
6   25-7-2021        7   JULY   2719848             2006       4
7   25-8-2021        8    AUG    462504             2006       9
8   25-9-2021        9   SEPT     25468             2015       6
9  25-10-2021       10    OCT   2564789             2015       9

In [393]:
#replace valies in specific limit

df.replace('FEB', method='bfill')

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\1474425867.py:3: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace('FEB', method='bfill')

         DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1    JAN   4642044             2015      10
1   25-2-2021        2    MAR   4642044             2020       6
2   25-3-2021        3    MAR   1245897             2014       8
3   25-4-2021        4  APRIL   1390411             2015       6
4   25-5-2021        5    MAY   6306064             2022       4
5   25-6-2021        6    JUN   6306064             2020       4
6   25-7-2021        7   JULY   2719848             2015       4
7   25-8-2021        8    AUG    462504             2006       9
8   25-9-2021        9   SEPT     25468             2015       6
9  25-10-2021       10    OCT   2564789             2015       9

In [430]:
#replace fix value using inplace parameter


df.replace('JAN', 'Tiger Jinda Hai', inplace=True)
df

         DATE  USER_ID           MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1  Tiger Jinda Hai   4642044             2015      10
1   25-2-2021        2              FEB   4642044             2020       6
2   25-3-2021        3              MAR   1245897             2014       8
3   25-4-2021        4            APRIL   1390411             2015       6
4   25-5-2021        5              MAY   6306064             2022       4
5   25-6-2021        6              JUN   6306064             2020       4
6   25-7-2021        7             JULY   2719848             2015       4
7   25-8-2021        8              AUG    462504             2006       9
8   25-9-2021        9             SEPT     25468             2015       6
9  25-10-2021       10              OCT   2564789             2015       9

In [431]:
df

         DATE  USER_ID           MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1  Tiger Jinda Hai   4642044             2015      10
1   25-2-2021        2              FEB   4642044             2020       6
2   25-3-2021        3              MAR   1245897             2014       8
3   25-4-2021        4            APRIL   1390411             2015       6
4   25-5-2021        5              MAY   6306064             2022       4
5   25-6-2021        6              JUN   6306064             2020       4
6   25-7-2021        7             JULY   2719848             2015       4
7   25-8-2021        8              AUG    462504             2006       9
8   25-9-2021        9             SEPT     25468             2015       6
9  25-10-2021       10              OCT   2564789             2015       9

# Pandas interpolate() method

used to fill NaN values in dataframe or series.
very powerful function
uses various interpolation techniques

In [481]:
df = pd.read_csv('Movieratingdata4.csv')
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      NaN   4642044              NaN     NaN     NaN
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      NaN   1390411           2015.0     NaN     6.0
4  25-05-2021      NaN   6306064              NaN       B     NaN
5  25-06-2021      NaN   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [482]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             10 non-null     object
 1   USER_ID          6 non-null      float64
 2   MOVIE_ID         10 non-null     int64
 3   PRODUCTION_YEAR  8 non-null      float64
 4   Section          7 non-null      object
 5   RATING           7 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 612.0+ bytes

In [483]:
df.fillna({'PRODUCTION_YEAR':2015},inplace=True)
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      NaN   4642044           2015.0     NaN     NaN
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      NaN   1390411           2015.0     NaN     6.0
4  25-05-2021      NaN   6306064           2015.0       B     NaN
5  25-06-2021      NaN   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [454]:
df['PRODUCTION_YEAR']=df['PRODUCTION_YEAR'].astype(int)

In [455]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             10 non-null     object
 1   USER_ID          6 non-null      float64
 2   MOVIE_ID         10 non-null     int64
 3   PRODUCTION_YEAR  10 non-null     int32
 4   Section          7 non-null      object
 5   RATING           7 non-null      float64
dtypes: float64(2), int32(1), int64(1), object(2)
memory usage: 572.0+ bytes

In [610]:
df = pd.read_csv('Movieratingdata4.csv')
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      NaN   4642044              NaN     NaN     NaN
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      NaN   1390411           2015.0     NaN     6.0
4  25-05-2021      NaN   6306064              NaN       B     NaN
5  25-06-2021      NaN   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [613]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             10 non-null     object
 1   USER_ID          6 non-null      float64
 2   MOVIE_ID         10 non-null     int64
 3   PRODUCTION_YEAR  8 non-null      float64
 4   Section          7 non-null      object
 5   RATING           7 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 612.0+ bytes

In [612]:
df.describe()

         USER_ID      MOVIE_ID  PRODUCTION_YEAR     RATING
count   6.000000  1.000000e+01         8.000000   7.000000
mean    6.333333  3.030513e+06      2014.375000   7.142857
std     3.559026  2.320577e+06         3.852179   2.478479
min     1.000000  2.546800e+04      2006.000000   4.000000
25%     4.000000  1.282026e+06      2014.750000   5.000000
50%     7.500000  2.642318e+06      2015.000000   8.000000
75%     8.750000  4.642044e+06      2015.000000   9.000000
max    10.000000  6.306064e+06      2020.000000  10.000000

In [442]:
#fill the value only in numerical columns

df.interpolate()

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\1444158805.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      2.0   4642044           2014.5     NaN     9.0
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      4.0   1390411           2015.0     NaN     6.0
4  25-05-2021      5.0   6306064           2017.5       B     5.0
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [443]:
df.interpolate(method="linear") #simple interpolate and linear parameter are same

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\2621325729.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear") #simple interpolate and linear parameter are same

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      2.0   4642044           2014.5     NaN     9.0
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      4.0   1390411           2015.0     NaN     6.0
4  25-05-2021      5.0   6306064           2017.5       B     5.0
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [444]:
df.interpolate(method="pad")

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\1339653710.py:1: FutureWarning: DataFrame.interpolate with method=pad is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.interpolate(method="pad")

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      1.0   4642044           2015.0       A    10.0
2  25-03-2021      3.0   1245897           2014.0       A     8.0
3  25-04-2021      3.0   1390411           2015.0       A     6.0
4  25-05-2021      3.0   6306064           2015.0       B     6.0
5  25-06-2021      3.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [408]:
df.interpolate(method="quadratic")

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\514417865.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="quadratic")

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section     RATING
0  25-01-2021      1.0   4642044      2015.000000       A  10.000000
1  25-02-2021      2.0   4642044      2014.074064     NaN   9.409799
2  25-03-2021      3.0   1245897      2014.000000     NaN   8.000000
3  25-04-2021      4.0   1390411      2015.000000     NaN   6.000000
4  25-05-2021      5.0   6306064      2018.407207       B   4.786185
5  25-06-2021      6.0   6306064      2020.000000       D   4.000000
6  25-07-2021      7.0   2719848      2015.000000       E   4.000000
7  25-08-2021      8.0    462504      2006.000000       B   9.000000
8  25-09-2021      9.0     25468      2015.000000       F  11.155079
9  25-10-2021     10.0   2564789      2015.000000       D   9.000000

In [459]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             10 non-null     object
 1   USER_ID          6 non-null      float64
 2   MOVIE_ID         10 non-null     int64
 3   PRODUCTION_YEAR  8 non-null      float64
 4   Section          7 non-null      object
 5   RATING           7 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 612.0+ bytes

In [487]:
#convert date columns into datetime


# type(df.DATE)
# type(df.DATE[0])      # Type Of Value
# df["DATE"].dtype

In [591]:
df = pd.read_csv('Movieratingdata4.csv',parse_dates=['DATE'] )
df.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\2863833479.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv('Movieratingdata4.csv',parse_dates=['DATE'] )

        DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0 2021-01-25      1.0   4642044           2015.0       A    10.0
1 2021-02-25      NaN   4642044              NaN     NaN     NaN
2 2021-03-25      3.0   1245897           2014.0     NaN     8.0
3 2021-04-25      NaN   1390411           2015.0     NaN     6.0
4 2021-05-25      NaN   6306064              NaN       B     NaN

In [592]:
#chek type of DATE columns values

type(df.DATE[0])

pandas._libs.tslibs.timestamps.Timestamp

In [593]:
df["DATE"].dtype

dtype('<M8[ns]')

In [594]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             10 non-null     datetime64[ns]
 1   USER_ID          6 non-null      float64
 2   MOVIE_ID         10 non-null     int64
 3   PRODUCTION_YEAR  8 non-null      float64
 4   Section          7 non-null      object
 5   RATING           7 non-null      float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 612.0+ bytes

In [602]:
#create date columns as a index

df = pd.read_csv('Movieratingdata4.csv',parse_dates=['DATE'] , index_col='DATE')
df.head(7)

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\783861925.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv('Movieratingdata4.csv',parse_dates=['DATE'] , index_col='DATE')

            USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
DATE
2021-01-25      1.0   4642044           2015.0       A    10.0
2021-02-25      NaN   4642044              NaN     NaN     NaN
2021-03-25      3.0   1245897           2014.0     NaN     8.0
2021-04-25      NaN   1390411           2015.0     NaN     6.0
2021-05-25      NaN   6306064              NaN       B     NaN
2021-06-25      NaN   6306064           2020.0       D     4.0
2021-07-25      7.0   2719848           2015.0       E     4.0

In [603]:
df.interpolate(method='time')

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\722817345.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='time')

              USER_ID  MOVIE_ID  PRODUCTION_YEAR Section     RATING
DATE
2021-01-25   1.000000   4642044      2015.000000       A  10.000000
2021-02-25   2.050847   4642044      2014.474576     NaN   8.949153
2021-03-25   3.000000   1245897      2014.000000     NaN   8.000000
2021-04-25   4.016393   1390411      2015.000000     NaN   6.000000
2021-05-25   5.000000   6306064      2017.459016       B   5.016393
2021-06-25   6.016393   6306064      2020.000000       D   4.000000
2021-07-25   7.000000   2719848      2015.000000       E   4.000000
2021-08-25   8.000000    462504      2006.000000       B   9.000000
2021-09-25   9.000000     25468      2015.000000       F   9.000000
2021-10-25  10.000000   2564789      2015.000000       D   9.000000

In [604]:
#changing index columns

df = pd.read_csv('Movieratingdata4.csv',parse_dates=['DATE'], index_col='MOVIE_ID' )
df

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\1536947339.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv('Movieratingdata4.csv',parse_dates=['DATE'], index_col='MOVIE_ID' )

               DATE  USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044  2021-01-25      1.0           2015.0       A    10.0
4642044  2021-02-25      NaN              NaN     NaN     NaN
1245897  2021-03-25      3.0           2014.0     NaN     8.0
1390411  2021-04-25      NaN           2015.0     NaN     6.0
6306064  2021-05-25      NaN              NaN       B     NaN
6306064  2021-06-25      NaN           2020.0       D     4.0
2719848  2021-07-25      7.0           2015.0       E     4.0
462504   2021-08-25      8.0           2006.0       B     9.0
25468    2021-09-25      9.0           2015.0       F     NaN
2564789  2021-10-25     10.0           2015.0       D     9.0

**Interpolation Formula is a technique mostly used to impute missing values in the data frame or series while preprocessing data.**

**Interpolation technique to use. One of:**

* ‘linear’: Ignore the index and treat the values as equally spaced. This is the only method supported on MultiIndexes.

* ‘time’: Works on daily and higher resolution data to interpolate given length of interval.

* ‘index’, ‘values’: use the actual numerical values of the index.

* ‘pad’: Fill in NaNs using existing values.

* ‘nearest’, ‘zero’, ‘slinear’, ‘quadratic’, ‘cubic’, ‘spline’, ‘barycentric’, ‘polynomial’: Passed to scipy.interpolate.interp1d. These methods use the numerical values of the index. Both ‘polynomial’ and ‘spline’ require that you also specify an order (int), e.g. df.interpolate(method='polynomial', order=5).

* ‘krogh’, ‘piecewise_polynomial’, ‘spline’, ‘pchip’, ‘akima’: Wrappers around the SciPy interpolation methods of similar names. See Notes.

* ‘from_derivatives’: Refers to scipy.interpolate.BPoly.from_derivatives which replaces ‘piecewise_polynomial’ interpolation method in scipy 0.18.

In [609]:
# df.interpolate()
# df.interpolate(method = 'linear')
df.interpolate(method = "time")

C:\Users\HP\AppData\Local\Temp\ipykernel_16780\3518627634.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method = "time")

NotImplementedError:

In [507]:
df

               DATE  USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044  2021-01-25      1.0           2015.0       A    10.0
4642044  2021-02-25      NaN              NaN     NaN     NaN
1245897  2021-03-25      3.0           2014.0     NaN     8.0
1390411  2021-04-25      NaN           2015.0     NaN     6.0
6306064  2021-05-25      NaN              NaN       B     NaN
6306064  2021-06-25      NaN           2020.0       D     4.0
2719848  2021-07-25      7.0           2015.0       E     4.0
462504   2021-08-25      8.0           2006.0       B     9.0
25468    2021-09-25      9.0           2015.0       F     NaN
2564789  2021-10-25     10.0           2015.0       D     9.0

In [622]:
df = pd.read_csv('Movieratingdata4.csv')
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      NaN   4642044              NaN     NaN     NaN
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      NaN   1390411           2015.0     NaN     6.0
4  25-05-2021      NaN   6306064              NaN       B     NaN
5  25-06-2021      NaN   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [627]:
df.ffill(inplace=True)
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      2.0   4642044           2014.5       A     9.0
2  25-03-2021      3.0   1245897           2014.0       A     8.0
3  25-04-2021      4.0   1390411           2015.0       A     6.0
4  25-05-2021      5.0   6306064           2017.5       B     5.0
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [628]:
df.set_index("RATING")

              DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section
RATING
10.0    25-01-2021      1.0   4642044           2015.0       A
9.0     25-02-2021      2.0   4642044           2014.5       A
8.0     25-03-2021      3.0   1245897           2014.0       A
6.0     25-04-2021      4.0   1390411           2015.0       A
5.0     25-05-2021      5.0   6306064           2017.5       B
4.0     25-06-2021      6.0   6306064           2020.0       D
4.0     25-07-2021      7.0   2719848           2015.0       E
9.0     25-08-2021      8.0    462504           2006.0       B
9.0     25-09-2021      9.0     25468           2015.0       F
9.0     25-10-2021     10.0   2564789           2015.0       D

In [629]:
df.describe()

        USER_ID      MOVIE_ID  PRODUCTION_YEAR     RATING
count  10.00000  1.000000e+01        10.000000  10.000000
mean    5.50000  3.030513e+06      2014.700000   7.300000
std     3.02765  2.320577e+06         3.537105   2.311805
min     1.00000  2.546800e+04      2006.000000   4.000000
25%     3.25000  1.282026e+06      2014.625000   5.250000
50%     5.50000  2.642318e+06      2015.000000   8.500000
75%     7.75000  4.642044e+06      2015.000000   9.000000
max    10.00000  6.306064e+06      2020.000000  10.000000

# Pandas loc & iloc method

In [630]:
df = pd.read_csv('MovieratingdataLOC-ILOC.csv')
df

         DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1    JAN   4642044             2015      10
1   25-2-2021        2    FEB   4642044             2020       6
2   25-3-2021        3    MAR   1245897             2014       8
3   25-4-2021        4  APRIL   1390411             2015       6
4   25-5-2021        5    MAY   6306064             2022       4
5   25-6-2021        6    JUN   6306064             2020       4
6   25-7-2021        7   JULY   2719848             2015       4
7   25-8-2021        8    AUG    462504             2006       9
8   25-9-2021        9   SEPT     25468             2015       6
9  25-10-2021       10    OCT   2564789             2015       9

In [511]:
#print single rows value #indexing
    
df.loc[0]

DATE               25-1-2021
USER_ID                    1
MONTHS                   JAN
MOVIE_ID             4642044
PRODUCTION_YEAR         2015
RATING                    10
Name: 0, dtype: object

In [512]:
#print multiple rows value-indexing 

df.loc[[0,4,8]]

        DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0  25-1-2021        1    JAN   4642044             2015      10
4  25-5-2021        5    MAY   6306064             2022       4
8  25-9-2021        9   SEPT     25468             2015       6

In [513]:
#print multiple rows value - slicing

df.loc[0:5]

        DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0  25-1-2021        1    JAN   4642044             2015      10
1  25-2-2021        2    FEB   4642044             2020       6
2  25-3-2021        3    MAR   1245897             2014       8
3  25-4-2021        4  APRIL   1390411             2015       6
4  25-5-2021        5    MAY   6306064             2022       4
5  25-6-2021        6    JUN   6306064             2020       4

In [514]:
#print specific row and specific columns values - indexing

df.loc[3,'PRODUCTION_YEAR']

2015

In [ ]:
# iloc

In [515]:
df = pd.read_csv("Movierating_groupby.csv")
df

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a        Holiday             2015       8
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10
9       10        g   Man in Black             2015       9

In [516]:
df.iloc[0]

USER_ID                  1
MOVIE_ID                 a
MOVIE_TITLE        Holiday
PRODUCTION_YEAR       2015
RATING                   8
Name: 0, dtype: object

In [517]:
df.iloc[0:4]

   USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a     Holiday             2015       8
1        2        b     Holiday             2016       6
2        3        b      Spyder             2020       8
3        4        b       Krish             2020       5

In [518]:
df.iloc[-1]

USER_ID                      10
MOVIE_ID                      g
MOVIE_TITLE        Man in Black
PRODUCTION_YEAR            2015
RATING                        9
Name: 9, dtype: object

In [519]:
df.iloc[-5:-1]

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10

In [520]:
df.iloc[1:7:2]

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
1        2        b        Holiday             2016       6
3        4        b          Krish             2020       5
5        6        d  Koyi mil gaya             2020       5

In [521]:
df

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a        Holiday             2015       8
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10
9       10        g   Man in Black             2015       9

In [522]:
df.iloc[3:8,0:3]

   USER_ID MOVIE_ID    MOVIE_TITLE
3        4        b          Krish
4        5        c  Koyi mil gaya
5        6        d  Koyi mil gaya
6        7        d         Spyder
7        8        e   Man in Black

In [523]:
df.iloc[1:5,1]

1    b
2    b
3    b
4    c
Name: MOVIE_ID, dtype: object

In [524]:
df.iloc[1:5,1:3]

  MOVIE_ID    MOVIE_TITLE
1        b        Holiday
2        b         Spyder
3        b          Krish
4        c  Koyi mil gaya

In [525]:
df.iloc[:,:3]

   USER_ID MOVIE_ID    MOVIE_TITLE
0        1        a        Holiday
1        2        b        Holiday
2        3        b         Spyder
3        4        b          Krish
4        5        c  Koyi mil gaya
5        6        d  Koyi mil gaya
6        7        d         Spyder
7        8        e   Man in Black
8        9        f         Spyder
9       10        g   Man in Black

In [526]:
df.iloc[1:5,:]

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4

In [527]:
df

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a        Holiday             2015       8
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10
9       10        g   Man in Black             2015       9

In [528]:
df.iloc[:,1::2]

  MOVIE_ID  PRODUCTION_YEAR
0        a             2015
1        b             2016
2        b             2020
3        b             2020
4        c             2019
5        d             2020
6        d             2015
7        e             2006
8        f             2015
9        g             2015

# groupby()

In [548]:
import pandas as pd

In [549]:
df = pd.read_csv("Movierating_groupby.csv")
df

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a        Holiday             2015       8
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10
9       10        g   Man in Black             2015       9

In [550]:
#passing a column name as a label

gr1 = df.groupby(by = 'MOVIE_TITLE') #output return in df objects
print(gr1)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002CF3F6F2300>

In [551]:
gr1.groups

{'Holiday': [0, 1], 'Koyi mil gaya': [4, 5], 'Krish': [3], 'Man in Black': [7, 9], 'Spyder': [2, 6, 8]}

In [552]:
df

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a        Holiday             2015       8
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10
9       10        g   Man in Black             2015       9

In [553]:
#using two column as label

df.groupby(['MOVIE_ID','PRODUCTION_YEAR']).groups

{('a', 2015): [0], ('b', 2016): [1], ('b', 2020): [2, 3], ('c', 2019): [4], ('d', 2015): [6], ('d', 2020): [5], ('e', 2006): [7], ('f', 2015): [8], ('g', 2015): [9]}

In [554]:
# @access groups 
for i in gr1:
    print(i,'\n\n')

('Holiday',    USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a     Holiday             2015       8
1        2        b     Holiday             2016       6)


('Koyi mil gaya',    USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5)


('Krish',    USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
3        4        b       Krish             2020       5)


('Man in Black',    USER_ID MOVIE_ID   MOVIE_TITLE  PRODUCTION_YEAR  RATING
7        8        e  Man in Black             2006       9
9       10        g  Man in Black             2015       9)


('Spyder',    USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
2        3        b      Spyder             2020       8
6        7        d      Spyder             2015       9
8        9        f      Spyder             2015      10)

In [564]:
df.groupby(['MOVIE_ID','PRODUCTION_YEAR']).sum().reset_index()

  MOVIE_ID  PRODUCTION_YEAR  USER_ID    MOVIE_TITLE  RATING
0        a             2015        1        Holiday       8
1        b             2016        2        Holiday       6
2        b             2020        7    SpyderKrish      13
3        c             2019        5  Koyi mil gaya       4
4        d             2015        7         Spyder       9
5        d             2020        6  Koyi mil gaya       5
6        e             2006        8   Man in Black       9
7        f             2015        9         Spyder      10
8        g             2015       10   Man in Black       9

In [540]:
# grp convert into list

list(gr1)

[('Holiday',
     USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
  0        1        a     Holiday             2015       8
  1        2        b     Holiday             2016       6),
 ('Koyi mil gaya',
     USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
  4        5        c  Koyi mil gaya             2019       4
  5        6        d  Koyi mil gaya             2020       5),
 ('Krish',
     USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
  3        4        b       Krish             2020       5),
 ('Man in Black',
     USER_ID MOVIE_ID   MOVIE_TITLE  PRODUCTION_YEAR  RATING
  7        8        e  Man in Black             2006       9
  9       10        g  Man in Black             2015       9),
 ('Spyder',
     USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
  2        3        b      Spyder             2020       8
  6        7        d      Spyder             2015       9
  8        9        f      Spyder             2015      10)]

In [541]:
#convert into dict

dict(list(gr1))

{'Holiday':    USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
 0        1        a     Holiday             2015       8
 1        2        b     Holiday             2016       6,
 'Koyi mil gaya':    USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
 4        5        c  Koyi mil gaya             2019       4
 5        6        d  Koyi mil gaya             2020       5,
 'Krish':    USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
 3        4        b       Krish             2020       5,
 'Man in Black':    USER_ID MOVIE_ID   MOVIE_TITLE  PRODUCTION_YEAR  RATING
 7        8        e  Man in Black             2006       9
 9       10        g  Man in Black             2015       9,
 'Spyder':    USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
 2        3        b      Spyder             2020       8
 6        7        d      Spyder             2015       9
 8        9        f      Spyder             2015      10}

In [542]:
df = pd.read_csv("Movierating_groupby.csv")

df

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a        Holiday             2015       8
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10
9       10        g   Man in Black             2015       9

In [558]:
#access single grp

c1 = df.groupby('MOVIE_ID').get_group('d')
c1

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9

In [559]:
c2 = df.groupby('PRODUCTION_YEAR').get_group(2015)
c2

   USER_ID MOVIE_ID   MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a       Holiday             2015       8
6        7        d        Spyder             2015       9
8        9        f        Spyder             2015      10
9       10        g  Man in Black             2015       9

In [560]:
len(c1)

2

In [561]:
df

   USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a        Holiday             2015       8
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10
9       10        g   Man in Black             2015       9

In [562]:
# applying basic function in group

gr1.sum()

               USER_ID MOVIE_ID  PRODUCTION_YEAR  RATING
MOVIE_TITLE
Holiday              3       ab             4031      14
Koyi mil gaya       11       cd             4039       9
Krish                4        b             2020       5
Man in Black        18       eg             4021      18
Spyder              19      bdf             6050      27

In [ ]:
# gr1.mean()  # Error : mean not possible for object datatype

In [563]:
#aggregate function


gr1.agg(['sum','max','min'])

              USER_ID         MOVIE_ID         PRODUCTION_YEAR              \
                  sum max min      sum max min             sum   max   min
MOVIE_TITLE
Holiday             3   2   1       ab   b   a            4031  2016  2015
Koyi mil gaya      11   6   5       cd   d   c            4039  2020  2019
Krish               4   4   4        b   b   b            2020  2020  2020
Man in Black       18  10   8       eg   g   e            4021  2015  2006
Spyder             19   9   3      bdf   f   b            6050  2020  2015

              RATING
                 sum max min
MOVIE_TITLE
Holiday           14   8   6
Koyi mil gaya      9   5   4
Krish              5   5   5
Man in Black      18   9   9
Spyder            27  10   8

# merge()

In [565]:
df1 = pd.DataFrame({'ID':[1,2,3,4,5], 'class':[11,22,33,44,55]})
df1

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55

In [566]:
df2 = pd.DataFrame({'ID':[1,2,3,4,5], 'name':['a','b','c','d','e']})
df2

   ID name
0   1    a
1   2    b
2   3    c
3   4    d
4   5    e

In [567]:
#merge data based on same columns name

pd.merge(df1,df2, on='ID')

   ID  class name
0   1     11    a
1   2     22    b
2   3     33    c
3   4     44    d
4   5     55    e

In [568]:
df3 = pd.DataFrame({'ID':[1,2,3,5], 'name':['a','b','c','e']})
df3

   ID name
0   1    a
1   2    b
2   3    c
3   5    e

In [569]:
#merge data based on same columns name but not same value

pd.merge(df1,df3, on='ID')

   ID  class name
0   1     11    a
1   2     22    b
2   3     33    c
3   5     55    e

In [570]:
#how parameter how='inner' or 'outer' or 'left' or 'right'

df1

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55

In [571]:
df3

   ID name
0   1    a
1   2    b
2   3    c
3   5    e

In [572]:
pd.merge(df1,df3, on="ID" , how='inner')

   ID  class name
0   1     11    a
1   2     22    b
2   3     33    c
3   5     55    e

In [573]:
pd.merge(df1,df3, on="ID" , how='outer')

   ID  class name
0   1     11    a
1   2     22    b
2   3     33    c
3   4     44  NaN
4   5     55    e

In [574]:
pd.merge(df1,df3, on="ID" , how='left')

   ID  class name
0   1     11    a
1   2     22    b
2   3     33    c
3   4     44  NaN
4   5     55    e

In [575]:
pd.merge(df1,df3, on="ID" , how='right')

   ID  class name
0   1     11    a
1   2     22    b
2   3     33    c
3   5     55    e

In [576]:
#which value belongs to which columns - indicator

pd.merge(df3,df1, on='ID', how='outer', indicator=True)

   ID name  class      _merge
0   1    a     11        both
1   2    b     22        both
2   3    c     33        both
3   5    e     55        both
4   4  NaN     44  right_only

In [577]:
pd.merge(df1,df3, on='ID', how='outer', indicator=True)

   ID  class name     _merge
0   1     11    a       both
1   2     22    b       both
2   3     33    c       both
3   4     44  NaN  left_only
4   5     55    e       both

In [578]:
#different value available in different dataframe

df4 = pd.DataFrame({'ID':[1,2,3,4,5], 'class':[11,22,33,44,55]})
df4

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55

In [579]:
df5 = pd.DataFrame({'ID':[6,7,8,9,10], 'name':[11,22,33,44,55]})
df5

   ID  name
0   6    11
1   7    22
2   8    33
3   9    44
4  10    55

In [583]:
pd.merge(df4,df5,left_index=True,right_index=True)

   ID_x  class  ID_y  name
0     1     11     6    11
1     2     22     7    22
2     3     33     8    33
3     4     44     9    44
4     5     55    10    55

# concat()

In [631]:
sr1 = pd.Series([0,1,2,22,44])
sr1

0     0
1     1
2     2
3    22
4    44
dtype: int64

In [632]:
sr2 = pd.Series([10,20,30,40,50])
sr2

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [637]:
pd.concat([sr1,sr2])

0     0
1     1
2     2
3    22
4    44
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [636]:
pd.concat([sr1,sr2], axis=1)

    0   1
0   0  10
1   1  20
2   2  30
3  22  40
4  44  50

In [638]:
df1 = pd.DataFrame({'ID':[1,2,3,4,5],'class':[11,22,33,44,55]})
df1

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55

In [639]:
df2 = pd.DataFrame({'ID':[60,70,80,90,100],'class':['a','b','c','d','e']})
df2

    ID class
0   60     a
1   70     b
2   80     c
3   90     d
4  100     e

In [640]:
#bydefalut row wise - axis=0

pd.concat([df1,df2])

    ID class
0    1    11
1    2    22
2    3    33
3    4    44
4    5    55
0   60     a
1   70     b
2   80     c
3   90     d
4  100     e

In [641]:
pd.concat([df1,df2], axis=1)

   ID class   ID class
0   1    11   60     a
1   2    22   70     b
2   3    33   80     c
3   4    44   90     d
4   5    55  100     e

In [642]:
#Single index- ignore_index

pd.concat([df1,df2], ignore_index=True)

    ID class
0    1    11
1    2    22
2    3    33
3    4    44
4    5    55
5   60     a
6   70     b
7   80     c
8   90     d
9  100     e

In [643]:
df1 = pd.DataFrame({'ID':[1,2,3,4,5],'class':[11,22,33,44,55]})
df1

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55

In [644]:
df2 = pd.DataFrame({'ID':[60,70,80,], 'class':['a','b','c']})
df2

   ID class
0  60     a
1  70     b
2  80     c

In [645]:
pd.concat([df1,df2],axis=1)

   ID class    ID class
0   1    11  60.0     a
1   2    22  70.0     b
2   3    33  80.0     c
3   4    44   NaN   NaN
4   5    55   NaN   NaN

In [646]:
pd.concat([df1,df2], axis=1, join='inner')

   ID class  ID class
0   1    11  60     a
1   2    22  70     b
2   3    33  80     c

In [647]:
#declare as a label - key=

pd.concat([df1,df2], keys=['DF_1','DF_2'], axis=1)

  DF_1        DF_2
    ID class    ID class
0    1    11  60.0     a
1    2    22  70.0     b
2    3    33  80.0     c
3    4    44   NaN   NaN
4    5    55   NaN   NaN

In [648]:
#declare as a label - key=

pd.concat([df1,df2], axis = 0, keys=['DF1','DF2'])

       ID class
DF1 0   1    11
    1   2    22
    2   3    33
    3   4    44
    4   5    55
DF2 0  60     a
    1  70     b
    2  80     c

In [649]:
#different different column names


df1 = pd.DataFrame({'ID1':[1,2,3,4,5],'class':[11,22,33,44,55]})
df1

   ID1  class
0    1     11
1    2     22
2    3     33
3    4     44
4    5     55

In [650]:
df2 = pd.DataFrame({'ID2':[1,2,3,4,5], 'Name':[11,22,33,44,55]})
df2

   ID2  Name
0    1    11
1    2    22
2    3    33
3    4    44
4    5    55

In [651]:
pd.concat([df1, df2])

   ID1  class  ID2  Name
0  1.0   11.0  NaN   NaN
1  2.0   22.0  NaN   NaN
2  3.0   33.0  NaN   NaN
3  4.0   44.0  NaN   NaN
4  5.0   55.0  NaN   NaN
0  NaN    NaN  1.0  11.0
1  NaN    NaN  2.0  22.0
2  NaN    NaN  3.0  33.0
3  NaN    NaN  4.0  44.0
4  NaN    NaN  5.0  55.0

In [653]:
pd.concat([df1, df2],axis=1)

   ID1  class  ID2  Name
0    1     11    1    11
1    2     22    2    22
2    3     33    3    33
3    4     44    4    44
4    5     55    5    55

# join()

In [654]:
#different different column names


df1 = pd.DataFrame({'ID1':[1,2,3,4,5],'class':[11,22,33,44,55]})
df1

   ID1  class
0    1     11
1    2     22
2    3     33
3    4     44
4    5     55

In [655]:
df2 = pd.DataFrame({'ID2':[1,2,3,4], 'Name':[11,22,33,44]})
df2

   ID2  Name
0    1    11
1    2    22
2    3    33
3    4    44

In [656]:
df1.join(df2)

   ID1  class  ID2  Name
0    1     11  1.0  11.0
1    2     22  2.0  22.0
2    3     33  3.0  33.0
3    4     44  4.0  44.0
4    5     55  NaN   NaN

In [657]:
#unmatched index


df2 = pd.DataFrame({'ID2':[1,2,3,4,5], 'Name':[11,22,33,44,55]}, index=['a','b','c','d','e'])
df2

   ID2  Name
a    1    11
b    2    22
c    3    33
d    4    44
e    5    55

In [658]:
df1.join(df2)

   ID1  class  ID2  Name
0    1     11  NaN   NaN
1    2     22  NaN   NaN
2    3     33  NaN   NaN
3    4     44  NaN   NaN
4    5     55  NaN   NaN

In [659]:
#unmatched element


df2 = pd.DataFrame({'ID2':[1,2,3], 'Name':[11,22,33]})
df2

   ID2  Name
0    1    11
1    2    22
2    3    33

In [661]:
df1.join(df2)

   ID1  class  ID2  Name
0    1     11  1.0  11.0
1    2     22  2.0  22.0
2    3     33  3.0  33.0
3    4     44  NaN   NaN
4    5     55  NaN   NaN

In [660]:
df1

   ID1  class
0    1     11
1    2     22
2    3     33
3    4     44
4    5     55

In [662]:
#same column name : use lprefix or rprefix

df2 = pd.DataFrame({'ID1':[1,2,3],'Name':[11,22,33]})
df2

   ID1  Name
0    1    11
1    2    22
2    3    33

In [666]:
df1.join(df2, lsuffix="_df1")

   ID1_df1  class  ID1  Name
0        1     11  1.0  11.0
1        2     22  2.0  22.0
2        3     33  3.0  33.0
3        4     44  NaN   NaN
4        5     55  NaN   NaN

In [667]:
df1.join(df2, rsuffix="_1")

   ID1  class  ID1_1  Name
0    1     11    1.0  11.0
1    2     22    2.0  22.0
2    3     33    3.0  33.0
3    4     44    NaN   NaN
4    5     55    NaN   NaN

# append()

In [668]:
#different different column names

df1 = pd.DataFrame({'ID':[1,2,3,4,5], 'class':[11,22,33,44,55]})
df1

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55

In [669]:
df2 = pd.DataFrame({'ID':[1,2,3,4,5], 'class':[11,22,33,44,55]})
df2

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55

In [671]:
frame = [df1,df2]

In [672]:
pd.concat(frame,ignore_index=True)

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55
5   1     11
6   2     22
7   3     33
8   4     44
9   5     55

In [673]:
res = pd.concat([df1,df2],ignore_index=True)
res

   ID  class
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55
5   1     11
6   2     22
7   3     33
8   4     44
9   5     55

In [674]:
df1.join(df2,rsuffix = "_1")

   ID  class  ID_1  class_1
0   1     11     1       11
1   2     22     2       22
2   3     33     3       33
3   4     44     4       44
4   5     55     5       55

In [675]:
# append is not for dataframe
df1.append(df2, ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'